### ISSUE TITLE
Failure to replicate results？

### ISSUE THREAD

**Issue by Betricy** [Syliz517/CLIP-ReID#21]
Use the veri data set to train and evaluate. The results are as follows：

2023-10-24 21:53:58,401 transreid.test INFO: Validation Results 
2023-10-24 21:53:58,402 transreid.test INFO: mAP: 75.5%
2023-10-24 21:53:58,402 transreid.test INFO: CMC curve, Rank-1  :92.0%
2023-10-24 21:53:58,402 transreid.test INFO: CMC curve, Rank-5  :94.4%
2023-10-24 21:53:58,402 transreid.test INFO: CMC curve, Rank-10 :95.9%

Rank_1 is 4.8% lower than in the paper...I double-checked the configs and ensured that the experiment settings were identical.

For reference, I'm attaching the training logs of the models:

[train_log_cnn_prom_veri.txt](https://github.com/Syliz517/CLIP-ReID/files/13116319/train_log_cnn_prom_veri.txt)

**Comment by Velpro-collab** [comment]
Traceback (most recent call last):
  File "/media/lele/c/zuozhigang/CLIP_ReID/Base/train_clipreid.py", line 89, in <module>
    do_train_stage2(
  File "/media/lele/c/zuozhigang/CLIP_ReID/Base/processor/processor_clipreid_stage2.py", line 98, in do_train_stage2
    loss = loss_fn(score, feat, target, target_cam, logits)
TypeError: loss_func() takes 3 positional arguments but 5 were given

请问一下，你们有没有遇到这个问题，如果有是怎么解决的？
